name: Continuous Integration
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2     
    - run: docker compose up -d --build
    
    - name: Testar aplicação
      run: |
        sleep 10
        curl -f http://localhost:5000 | grep "Contador de Visitas"
    - run: | 
        sleep 10
        curl -f http://localhost:5000 | grep "Contador de Visitas"
        
    - name: Encerrar containers
      run: docker compose down
    

